PREFIX wtr: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ont: <http://purl.org/ontology/mo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX goat: <http://www.holygoat.co.uk/owl/redwood/0.1/tags/>
PREFIX goa2: <http://www.holygoat.co.uk/owl/redwood/0.1/tags/>
PREFIX jamendo: <http://dbtune.org/jamendo/tag/>

SELECT ?name
WHERE { ?alb foaf:made ?art. ?alb goat:taggedWithTag jamendo:pop. ?alb <http://www.holygoat.co.uk/owl/redwood/0.1/tags/taggedWithTag> jamendo:jazz. ?alb goat:taggedWithTag jamendo:rock. }
